### ISSUE TITLE
Handle Form Post

### ISSUE THREAD

**Issue by LotharMaerkle** [mocks-server/core#201]
Still there are APIs out that requires body encoding application/x-www-form-urlencoded (consider mocking OIDC)

expressjs is configured to parse JSON, but not the form encoding
add export 
const urlencodedBodyParser = express.urlencoded({ extended: true })
to middleware.js and apply in Server.js to the expressjs server

**Describe alternatives you've considered**
Not clear how to do that in a safe way through plugin as the expressjs is not exposed

**Comment by javierbrea** [comment]
Hi @LotharMaerkle,

About the alternative you've considered, I think it's better to add it to the core instead of using a plugin. There is an issue about exposing some options to configure `jsonBodyParser`, so this new feature could be configurable with that options too. I will add a comment to #192.
